name: CI

on: 
  push:
  pull_request:

jobs:
  docker-build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build & test upto builder stage
        run: |
          docker build --target builder -t tax_bracket_ingest:ci .
          docker run --rm tax_bracket_ingest:ci sh -c "pip install -r requirements.txt && pytest --cov=tax_bracket_ingest --cov-report=xml:coverage.xml"

      - name: Extract coverage report
        run: |
          mkdir -p coverage
          mv coverage.xml coverage/

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        continue-on-error: true
        with:
          files: coverage/coverage.xml
          verbose: true
          